ZeetecShop/urls.py
from django.conf.urls import url, include, static
from django.conf import settings
from django.contrib import admin
from .views import index, detailGoods

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name="index"),
    url(r'^webAdmin/', include('webAdmin.urls', namespace = 'webAdmin')),
    url(r'^barang/(?P<slugify>[\w-]+)/$', detailGoods, name = 'detailGoods'),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webAdmin/urls.py
from django.conf.urls import url
from .views import (
    index, 
    user, 
    login, 
    logout,
    register,
    createGoods,
    updateGoods,
    deleteGoods,
)

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^user/', user, name="user"),
    url(r'^login/', login, name="login"),
    url(r'^register/', register, name="register"),
    url(r'^logout/', logout, name="logout"),
    url(r'^createGoods/', createGoods, name="crtGoods"),
    url(r'^updateGoods/(?P<dynamicID>[0-9]{1,2})', updateGoods, name="uptGoods"),
    url(r'^deleteGoods/(?P<dynamicID>[0-9]{1,3})', deleteGoods, name="dltGoods")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title_head %}
      
    {% endblock title_head %}

    {% include "snippets/link.html" %}
    
    {% block style %}
      
    {% endblock style %}

</head>
<body>
    {% block body %}
      
    {% endblock body %}


</body>
{% include "snippets/script.html" %}
{% block script %}
  
{% endblock script %}
</html>

templates/detailGoods.html
{% extends "base.html" %}
{% load static %}

{% block title_head %}
    <title>ZeetecShop | Detail Barang</title>
{% endblock title_head %}

{% block style %}
  
{% endblock style %}

{% block body %}
    <h1 class="title">{{ goods.nameGoods }} </h1>
{% endblock body %}

{% block script %}
  
{% endblock script %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title_head %}
    <title>ZeetecShop | {{ title_head }}</title>
{% endblock title_head %}

{% block style %}
    <link rel="stylesheet" href="{% static 'asset/css/style.css' %}">
{% endblock style %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-light bg-dark sticky-top">
        <img src="{% static 'asset/images/logo.png' %}" alt="" class="logo">
        <a class="navbar-brand" href="#">Zeetec Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Goods</a>
            </li>
            <li class="nav-item">
                <img class="nav-link buttonSearch" src="{% static 'asset/images/search.png' %}" alt="">
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webAdmin:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <h6 class="nav-link">{{ user }}</h6>
                </li>
            {% else %}
                <li class="nav-item login">
                    <a class="nav-link" href="{% url 'webAdmin:login' %}">Login</a>
                </li>
                <li class="nav-item register">
                    <a class="nav-link" href="{% url 'webAdmin:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        </div>
    </nav>

    <div class="bd-example">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'asset/images/image1.png' %}" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>First slide label</h5>
                        <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'asset/images/image2.png' %}" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Second slide label</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'asset/images/image3.png' %}" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Third slide label</h5>
                        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <div class="cardGoods" id="cardGoods">
        {% for goods in allGoods %}
            {% if forloop.counter > 6 %}
                <div class="card card{{forloop.counter}} lane2">
            {% elif forloop.counter > 12 %}
                <div class="card card{{forloop.counter}} lane3">
            {% else %}
                <a href="/barang/{{goods.slugifyGoods}}">
                    <div class="card card{{forloop.counter}} lane1">
            {% endif %}
            
                <img src="media/{{goods.imagesGoods}}" class="card-img-top" alt="...">
                <h6 id="nameGoods">{{goods.nameGoods}}</h6>
                <h6>Rp {{goods.priceGoods | intcomma}}</h6>
                <div class="rateStar" id="">
                    
                    {% if goods.rateGoods > 0 %}
                        <img src="{% static 'asset/images/rateStarChecked.png' %}" alt="" class="star star1" id="star1">
                    {% else %}
                        <img src="{% static 'asset/images/rateStar.png' %}" alt="" class="star star1" id="star1">
                    {% endif %}
                    {% if goods.rateGoods > 1 %}
                        <img src="{% static 'asset/images/rateStarChecked.png' %}" alt="" class="star star2" id="star2">
                    {% else %}
                        <img src="{% static 'asset/images/rateStar.png' %}" alt="" class="star star2" id="star2">
                    {% endif %}    
                    {% if goods.rateGoods > 2 %}
                        <img src="{% static 'asset/images/rateStarChecked.png' %}" alt="" class="star star3" id="star3">
                    {% else %}
                        <img src="{% static 'asset/images/rateStar.png' %}" alt="" class="star star3" id="star3">
                    {% endif %}    
                    {% if goods.rateGoods > 3 %}
                        <img src="{% static 'asset/images/rateStarChecked.png' %}" alt="" class="star star4" id="star4">
                    {% else %}
                        <img src="{% static 'asset/images/rateStar.png' %}" alt="" class="star star4" id="star4">
                    {% endif %}    
                    {% if goods.rateGoods > 4 %}
                        <img src="{% static 'asset/images/rateStarChecked.png' %}" alt="" class="star star5" id="star5">
                    {% else %}
                        <img src="{% static 'asset/images/rateStar.png' %}" alt="" class="star star5" id="star5">
                    {% endif %}

                </div>
            </div>
            </a>
        {% endfor %}
    </div>

{% endblock body %}

{% block script %}

{% endblock script %}